name: Pint

on: [push]

jobs:
   pint:
      runs-on: ubuntu-latest
      
      steps:
         -  name: Checkout code
            uses: actions/checkout@v3
            with:
               ref: ${{ github.head_ref }}
         
         -  name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
               php-version: 8.1
               extensions: mbstring, redis
               coverage: none
               tools: php-cs-fixer, phpunit
         
         -  name: Validate Composer
            run: composer validate
         
         -  name: Install Composer dependencies
            run: composer install --prefer-dist --no-interaction
         
         -  name: Laravel Pint checks
            run: vendor/bin/pint --test
